"""Public service notices describing actual product behavior."""
from html import escape
from fastapi.responses import HTMLResponse

def install_pages(app,config):
    def page(title,body):
        return HTMLResponse('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(title)+' · Valases Jobs</title><link rel="stylesheet" href="/assets/workspace.css?v=launch-1"></head><body><main class="service-notice"><a href="/">← Valases Jobs</a><h1>'+escape(title)+'</h1>'+body+'</main></body></html>')
    def contact():
        return '<a href="mailto:'+escape(config.support_email,quote=True)+'">'+escape(config.support_email)+'</a>' if config.support_email else 'Support contact will be configured before public launch.'
    @app.get('/privacy',response_class=HTMLResponse)
    def privacy():
        return page('Privacy notice','<p>'+escape(config.company_name)+' operates Valases Jobs.</p><h2>Your account and résumé</h2><p>We store your name, email, password hash, saved jobs, résumé text, preferences and alert choices to provide this service. Uploaded files are read temporarily and are not retained. You choose whether to save the extracted text. Production résumé text and queued email content are encrypted using an application key.</p><h2>Applications and payments</h2><p>Applying opens the employer’s application form on Valases. You review and submit there; your Jobs profile is not silently transferred. Employers manage the applications they receive separately. Cashfree processes payments; we retain order identifiers, amount, currency and entitlement status. We do not store card details.</p><h2>Email and cookies</h2><p>We send account verification and recovery emails when requested. Matching alerts are optional, require an active plan and verified email, and can be disabled in your account or through the unsubscribe link. A necessary session cookie keeps you signed in. This release has no advertising trackers.</p><h2>Access and deletion</h2><p>Download your account data or delete your account in the account menu. Deletion removes the active Jobs profile, sessions, saved jobs, feedback, alert history and queued messages. Payment records are detached from your account. Employer-held applications and payment-provider records are managed separately. Expired sessions and action links are regularly removed; sent and failed email records are removed after 30 days. Infrastructure backups follow the hosting operator’s retention schedule.</p><h2>Questions</h2><p>'+contact()+'</p>')
    @app.get('/terms',response_class=HTMLResponse)
    def terms():
        return page('Terms of service','<p>Valases Jobs helps candidates discover employer-listed vacancies. Search and applications are free.</p><h2>Paid access</h2><p>₹79 buys 30 days of full matching access and optional daily alerts. Renewal is manual; there is no automatic recurring debit in this release. A renewal adds 30 days to an active plan, or starts 30 days from verified payment when the previous plan has ended. Access is granted only after payment verification. The checkout amount is ₹79 INR.</p><h2>Matching and vacancies</h2><p>Matches use skills claimed in your résumé and the preferences you enter. Matching does not verify proficiency or predict selection. Review the employer’s requirements before applying. Employers control vacancy availability and hiring decisions; listings may close. Payment does not guarantee a match, interview, offer or job.</p><h2>Your responsibilities</h2><p>Provide accurate information, protect your account, and upload only documents you have permission to use. Do not submit abusive content or attempt to disrupt the service. Employers must publish accurate jobs and must not seek payment from candidates as a condition of applying.</p><h2>Billing support</h2><p>For duplicate charges, missing access or service issues, contact '+contact()+'. Include the payment order reference. Never send card details or passwords. Refund requests are reviewed by support; payment-provider processing times may apply.</p><h2>Service operator</h2><p>'+escape(config.company_name)+'. Contact: '+contact()+'.</p>')
    @app.get('/contact',response_class=HTMLResponse)
    def support():
        return page('Support','<p>For account help, payment issues or suspicious vacancies, contact '+contact()+'.</p><p>Include the job title and company, or your payment order reference. Do not include passwords, card details or unnecessary résumé information.</p><p>You can turn off alerts, export your data or delete your account from the account menu.</p>')
